# Generated by Django 4.0.5 on 2022-08-11 08:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_tasks_user_id_alter_tasks_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 8, 58, 46, 33392)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 8, 58, 46, 33392)),
        ),
    ]
