# Generated by Django 4.0.5 on 2022-08-11 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tasks_user_id_alter_tasks_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 10, 34, 41, 146979)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 10, 34, 41, 146979)),
        ),
    ]
